### ISSUE TITLE
Restructure tables

### ISSUE THREAD

**Issue by aubundy** [aTmb405/breads-server#21]
- [x] How to separate existing table?

- User Tags (user_id, tag_id)
- User Readings (user_id, reading_id)
- Reading Tags (reading_id, tag_id)
- Favorites
- Subscriptions
- Users
- Readings
- Tags

**Comment by aTmb405** [comment]
#11

**Comment by aubundy** [comment]
return tag info in readings apicall
    normalize tag info into
        readings - each reading has tags key with array of tag ids
        tags - object key is tag id, value is array of tag_name, reading_id, user_id objects
    
        I'm returning tags id with readings now. 
        need to add user readings table - how to transfer data from one table to another?
            user id, reading id, created date
             IS READING_TAGS ALREADY THE USER READINGS TABLE I NEED?
                maybe a user tags table, user readings table, and reading tags table
                    user -> tags, user -> readings, reading -> tags
