### ISSUE TITLE
Cannot delete reading

### ISSUE THREAD

**Issue by aubundy** [aTmb405/breads-server#48]
Due to the structure of some SQL tables, some readings cannot be deleted:

- [ ]  if the reading is favorited
- [ ] if the reading has associated tags

**Comment by aubundy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot delete reading if it is favorited](https://trello.com/c/ByVR5QHw/7-cannot-delete-reading-if-it-is-favorited)

**Comment by ToGenplusplus** [comment]
Hello, can I work on resolving this issue, I have an idea of how to do this but i would like a little clarification to make sure i resolve this properly.

**Comment by aubundy** [comment]
@ToGenplusplus if a reading id is found in the `reading_tags` or `favorites` table, we need to delete the row containing that reading id before deleting the appropriate row in the `user_readings` table. The current query to delete readings can be found in `queries/reading.js` line 6
