### ISSUE TITLE
Full Unicode in db

### ISSUE THREAD

**Issue by aubundy** [aTmb405/breads-server#49]
Some articles will have emojis in either the title or description, but the db is not set up for full unicode support, so these articles can't be saved to the db. We need to transition from utf8 to utf8mb4 tables

Resources:

- https://mathiasbynens.be/notes/mysql-utf8mb4#character-sets
- https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5

**Comment by aubundy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Full Unicode in db](https://trello.com/c/Jt5xtupZ/12-full-unicode-in-db)

**Comment by Areezy** [comment]
Hello! can I work on this ? I have read the resources you provided above and the contribution guide of course.

**Comment by aubundy** [comment]
@Areezy Yes, thank you! I'll add you as the assignee

**Comment by Areezy** [comment]
My approach to this is creating a new sql file which alters the tables to add support for utf8mb4 characters. Is that okay?

**Comment by aubundy** [comment]
Yes, that would be great. In the PR message, could you also write up an `ALTER TABLE` statement that accomplishes the same thing? I will need to use it to update the production db

**Comment by Areezy** [comment]
The plan was to add those alter table statements in the new file I would create. So you could just grab all the statements from there and run it on the production db. Would it still be necessary to add them to the PR message ?

**Comment by aubundy** [comment]
@Areezy no need to add them to PR message. I did just request a change if you want to take a look

**Comment by Areezy** [comment]
Okay, I am taking a look now
